cmake_minimum_required(VERSION 3.8)
project(moveit_test_constraints)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(moveit_msgs REQUIRED)
find_package(shape_msgs REQUIRED)
find_package(moveit_ros_warehouse REQUIRED)
find_package(warehouse_ros REQUIRED)
add_executable(save_constraints src/save_constraints.cpp)
target_compile_features(save_constraints PUBLIC cxx_std_17)
ament_target_dependencies(save_constraints rclcpp moveit_msgs shape_msgs moveit_ros_warehouse warehouse_ros)
install(TARGETS save_constraints DESTINATION lib/${PROJECT_NAME})
ament_package()
