format_version: 1
frame_id: link_base
pallet_geometry:
  length_x_m: 0.5
  length_y_m: 0.5
  surface_thickness_m: 0.005
  origin: corner_of_top_face
localization:
  marker_id: 14
  required_samples: 27
  position_tolerance_m: 0.005
  angle_tolerance_deg: 2.0
  marker_offset_rpy_deg:
  - 0.0
  - 0.0
  - 0.0
  marker_offset_xyz_m:
  - 0.0
  - 0.0
  - 0.0213
pallet_pose:
  position_m:
  - 0.4924156959949447
  - -0.6822023079779164
  - -0.04314690818251143
  orientation_xyzw:
  - -0.005835848387898373
  - 0.004664320074044492
  - 0.7484316939673658
  - 0.6631698021298765
pre_place_pose:
  frame_id: pallet_frame
  position_m:
  - 0.0
  - 0.0
  - 0.0
  rotate_item_90_deg: false
  keep_tcp_roll_pitch: false
  add_placed_item_obstacle: false
