#include <cmath>
#include <filesystem>
#include <stdexcept>
#include <rclcpp/rclcpp.hpp>
#include <warehouse_ros/database_loader.h>
#include <moveit/warehouse/constraints_storage.hpp>
#include <moveit_msgs/msg/orientation_constraint.hpp>
#include <moveit_msgs/msg/position_constraint.hpp>
#include <shape_msgs/msg/solid_primitive.hpp>

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  auto node = std::make_shared<rclcpp::Node>("save_test_constraints");
  try {
    const auto path = node->declare_parameter<std::string>(
      "warehouse_host", "/workspace/results/moveit_warehouse.sqlite");
    node->declare_parameter<std::string>("warehouse_plugin",
      "warehouse_ros_sqlite::DatabaseConnection");
    node->declare_parameter<int>("warehouse_port", 33829);
    const auto robot = node->declare_parameter<std::string>("robot", "UF_ROBOT");
    const auto group = node->declare_parameter<std::string>("group", "uf850");
    const auto tolerance = node->declare_parameter<double>("tilt_tolerance_rad", std::acos(-1.)/6.);
    const auto overwrite = node->declare_parameter<bool>("overwrite", false);
    const auto name = node->declare_parameter<std::string>("constraint_name", "tcp_down_yaw_free");
    const auto height_enabled = node->declare_parameter<bool>("clearance_constraint_enabled", false);
    const auto floor = node->declare_parameter<double>("tcp_min_z_m", .4364);
    const auto ceiling = node->declare_parameter<double>("tcp_max_z_m", 10.4364);
    if (name.empty() || !std::isfinite(floor) || !std::isfinite(ceiling) || floor >= ceiling) {
      throw std::runtime_error("invalid constraint name or TCP height interval");
    }
    if (!std::isfinite(tolerance) || tolerance <= 0 || tolerance > std::acos(-1.)/6.) {
      throw std::runtime_error("tilt_tolerance_rad must be in (0, pi/6] (up to 30 degrees)");
    }
    std::filesystem::create_directories(std::filesystem::path(path).parent_path());
    warehouse_ros::DatabaseLoader loader(node);
    auto connection = loader.loadDatabase();
    connection->setParams(path, 33829, 5.0);
    if (!connection->connect()) throw std::runtime_error("warehouse connection failed");
    moveit_warehouse::ConstraintsStorage storage(connection);
    moveit_msgs::msg::Constraints c;
    c.name = name;
    moveit_msgs::msg::OrientationConstraint o;
    o.header.frame_id = "link_base";
    o.link_name = "link_tcp";
    // Tool Z points down: 180 degrees about base X. Yaw remains free.
    o.orientation.x = 1.;
    o.orientation.w = 0.;  // Quaternion messages default to w=1, not zero.
    o.parameterization = moveit_msgs::msg::OrientationConstraint::ROTATION_VECTOR;
    o.absolute_x_axis_tolerance = o.absolute_y_axis_tolerance = tolerance;
    o.absolute_z_axis_tolerance = std::acos(-1.);
    o.weight = 1.;
    c.orientation_constraints.push_back(o);
    if (height_enabled) {
      moveit_msgs::msg::PositionConstraint p;
      p.header.frame_id = "link_base";
      p.link_name = "link_tcp";
      p.weight = 1.;
      shape_msgs::msg::SolidPrimitive box;
      box.type = shape_msgs::msg::SolidPrimitive::BOX;
      box.dimensions = {4., 4., ceiling - floor};
      geometry_msgs::msg::Pose center;
      center.position.z = (floor + ceiling) / 2.;
      center.orientation.w = 1.;
      p.constraint_region.primitives.push_back(box);
      p.constraint_region.primitive_poses.push_back(center);
      c.position_constraints.push_back(p);
    }
    // Do not silently overwrite an operator-edited named constraint.
    if (overwrite || !storage.hasConstraints(c.name, robot, group)) {
      storage.addConstraints(c, robot, group);
    }
    moveit_warehouse::ConstraintsWithMetadata saved;
    if (!storage.getConstraints(saved, c.name, robot, group) ||
        saved->orientation_constraints.size() != 1) {
      throw std::runtime_error("constraint readback failed");
    }
    // Repair only the exact malformed quaternion generated by our first version.
    // Preserve any independently edited constraint instead of overwriting it.
    const auto & old = saved->orientation_constraints.front();
    if (old.header.frame_id == o.header.frame_id && old.link_name == o.link_name &&
        old.orientation.x == 1. && old.orientation.y == 0. &&
        old.orientation.z == 0. && old.orientation.w == 1. &&
        old.parameterization == o.parameterization &&
        old.absolute_x_axis_tolerance == .02 && old.absolute_y_axis_tolerance == .02 &&
        old.absolute_z_axis_tolerance == std::acos(-1.)) {
      auto repaired = static_cast<const moveit_msgs::msg::Constraints &>(*saved);
      repaired.orientation_constraints.front().orientation.w = 0.;
      storage.addConstraints(repaired, robot, group);
      if (!storage.getConstraints(saved, c.name, robot, group) ||
          saved->orientation_constraints.front().orientation.w != 0.) {
        throw std::runtime_error("quaternion repair readback failed");
      }
      RCLCPP_INFO(node->get_logger(), "Repaired malformed [1,0,0,1] quaternion to [1,0,0,0]");
    }
    const auto & actual = saved->orientation_constraints.front();
    if (overwrite && saved->position_constraints != c.position_constraints) {
      throw std::runtime_error("position constraint readback mismatch");
    }
    if (overwrite && (actual.orientation.x != 1. || actual.orientation.w != 0. ||
        actual.absolute_x_axis_tolerance != tolerance ||
        actual.absolute_y_axis_tolerance != tolerance ||
        actual.absolute_z_axis_tolerance != std::acos(-1.))) {
      throw std::runtime_error("updated constraint readback mismatch");
    }
    RCLCPP_INFO(node->get_logger(), "Available: %s robot=%s group=%s db=%s tilt=%.6f/%.6f yaw=%.6f",
      c.name.c_str(), robot.c_str(), group.c_str(), path.c_str(),
      actual.absolute_x_axis_tolerance, actual.absolute_y_axis_tolerance,
      actual.absolute_z_axis_tolerance);
  } catch (const std::exception & e) {
    RCLCPP_ERROR(node->get_logger(), "%s", e.what());
    rclcpp::shutdown();
    return 1;
  }
  rclcpp::shutdown();
  return 0;
}
